### ISSUE TITLE
Auto discover feature directories on installed Django apps

### ISSUE THREAD

**Issue by mixxorz** [behave/behave-django#10]
Moved from https://github.com/mixxorz/behave-django/issues/39

**Comment by bittner** [comment]
@seocam Can you give us a motivation on that? "Installed apps" is "all apps from `INSTALLED_APPS`". That could be some you develop yourself (and have "locally", as subdirectories of your project) and some that are simply part of your site-packages (apps installed via pip in your virtualenv).

If the latter are picked should `behave` execute BDD tests from them too?

**Comment by omaraboumrad** [comment]
While i'm not the original poster, i would like to answer that question.

> If the latter are picked should behave execute BDD tests from them too?

No, similar to running standard Django tests, it doesn't pickup the installed apps in site-packages, it only runs the tests for the local apps.

**Comment by bittner** [comment]
So, it's really about the local apps of your Django project? We shouldn't use `INSTALLED_APPS` for detecting but simply crawl the project directory tree. Is this sufficient? -- _Note that we should then change the issue title to reflect this finding._

This _is_ already supported, though, by `behave` via its [configuration file](https://behave-django.readthedocs.io/en/latest/usage.html#behave-configuration-file). Is that not sufficient? If not, why?

**Comment by omaraboumrad** [comment]
Right, this is mostly convenience, similar to the convenience provided [django.test.runner.DiscoverRunner](https://docs.djangoproject.com/en/1.10/topics/testing/advanced/#using-different-testing-frameworks) which would find any file called `test*.py` and run it.

P.S. This is my own thoughts on the subject and doesn't reflect the original poster's intent. Perhaps he has other intentions for having `INSTALLED_APPS` specific lookups. (Possibly disabling finding an apps' features if that app _is_ in the project directory but not in `INSTALLED_APPS`)

**Comment by bittner** [comment]
Is this feature request still valid? Can anyone who sees actual value in this make a :+1: on this issue, please?

I would otherwise close the issue.
