### ISSUE TITLE
Move docs to ReadTheDocs and setup automated doc builds

### ISSUE THREAD

**Issue by mixxorz** [behave/behave-django#11]
Currently, we're hosting our docs on pythonhosted.org. While this is fine, we can't automate the process of releasing documentation. Moving to RTD will allow us to automate doc uploading.

I've actually never done something like this before. I'm assuming we setup some task on the CI server that uploads the docs to RTD?

**Comment by jenisys** [comment]
You just need to register/create the project at readthedocs.org. It will ask you for the github project repository and inject its hooks in the github project repository. Every commit to the github repository will trigger a rebuild on readthedocs.org. Stable versions are probably detected when you tag or release the project.

**Comment by bittner** [comment]
I've seen RTD doesn't always rebuild the docs automatically (not 100% sure why). It's  possible to make triggering that automatic though very easily ([example from a project of mine](https://github.com/Organice/django-organice/blob/master/.travis.yml#L23)).
