### ISSUE TITLE
Getting more programmatic flexibility on the testcase type used in scenarios

### ISSUE THREAD

**Issue by LucidDan** [behave/behave-django#115]
Hi folks,

Please bear with me here, as I fully acknowledge I'm still a beginner on both behave and Django TestCase implementations. I've been happily using pytest for years, but frustrations with the state of pytest-bdd drove me to finally jump ship to behave for BDD-related stuff. Apologies in advance for any lack of understanding, but perhaps if nothing else, my naïve perspective can help reveal areas documentation might be improved.

I'm working on a project where for various reasons I'm unable to take advantage of the built in liveserver, and to save some resources and test time, I'd rather not spin the liveserver up at all. At the same time, it occurs to me that there might be some features or scenarios where I don't need TransactionTestCase, but others where I do.

Is there a reasonably easy way for me to, or does it even make sense to have a way, to programmatically change the testclass that will be used for a particular scenario or feature? For example, using behave tags to run some scenarios as SimpleTestCase, others as TransactionTestCase, and potentially even some with the liveserver?

Or does this just not make any sense at all, and I'm approaching this completely the wrong way? Is it not possible/desirable to selectively change the testclass?

**Comment by bittner** [comment]
I can't comment properly now as I'm on the beach, currently. 🏖️ However, I encourage you to find out and find an intuitive, the most intuitive way, ideally.

Just a comment on your history, my personal preference would be to integrate pytest style testing into behave, or at least behave-django. See https://github.com/behave-contrib/behave-pytest/issues/1 for example.

I've also recently added [page objects](https://behave-django.readthedocs.io/en/stable/pageobject.html) to allow for a clean approach on BDD testing typical websites.

Whatever helps to make testing easy, intuitive, straightforward, yet still keeping a clean approach, let's make it come true if it's not possible yet.

**Comment by bittner** [comment]
With our test setup in this project [we use "decorators"](https://github.com/behave/behave-django/blob/master/tests/acceptance/features/fixture-loading.feature#L1) in the `.feature` files, and [selectively run](https://github.com/behave/behave-django/blob/master/tox.ini#L26-L27) the related tests using behave's `--tags` option.

Does that already answer your question?

**Comment by bittner** [comment]
> For example, using behave tags to run some scenarios as SimpleTestCase, others as TransactionTestCase, and potentially even some with the liveserver?

@LucidDan Yes. See [our test setup](https://github.com/behave/behave-django/blob/master/tox.ini#L27-L29) for an example.

Does that answer your questions? If yes, please let us know and close this issue. Thank you!

**Comment by bittner** [comment]
I assume your problems are solved. Take a look at how we do it in our own project here, otherwise.

Let us know if you have any other question!
