### ISSUE TITLE
how to assess test case code coverage?

### ISSUE THREAD

**Issue by masoodkamyab** [behave/behave-django#119]
Hi, I'm new in behave and I've written a test for my project, so I need to need evaluate the coverage of my test cases. I use this command `coverage run --source='.' -m behave` instead of `python manage.py behave`  and didn't run django test setup to create test database.
how can I get coverage with `python manage.py behave` ?

**Comment by Blue-Hope** [comment]
I used coveragepy's API like this
```py
import coverage

def before_all(context):
    cov = coverage.Coverage()
    cov.start()
    context.cov = cov


def after_all(context):
    cov = context.cov
    cov.stop()
    cov.save()
    cov.html_report(directory="./cov")
```

**Comment by bittner** [comment]
@masoodkamyab @Blue-Hope Would anyone of you like to try a contribution to [behave-django](https://behave-django.readthedocs.io/)'s or [Behave](https://behave.readthedocs.io/en/latest/)'s documentation?

I think this topic is of broad, general interest and very well worth to be mentioned in the docs.

**Comment by Blue-Hope** [comment]
I'll write on behave repo too.
+ 
I am using mock well now, but at first it was not easy to introduce due to simple documentation. Is it okay if I add a little more stale content to behave and behave-django as a single document about mocking? (Behave-django's mock-related process is slightly different, so both documents seem to be needed)

**Comment by bittner** [comment]
Yes, that's okay.

behave-django is just an integration layer for Django. In theory, all generic instructions should go into the Behave docs, and the django-behave docs should then point to there when appropriate.

**Comment by bittner** [comment]
This is now documented in a [dedicated chapter](https://behave-django.readthedocs.io/en/latest/testcoverage.html) in our docs. 

Thanks @Blue-Hope for contributing! :100:
