### ISSUE TITLE
Remove deprecation code (old hooks)

### ISSUE THREAD

**Issue by bittner** [behave/behave-django#12]
@mixxorz I plan to remove the [old hooks functions](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L72) that currently print out a deprecation warning. This is just one of the things I plan for the next version 0.4.0:

1. Have deprecated code removed
1. Switch from optparse to argparse
1. Maybe add some handy, optional helpers (Selenium helpers for the moment, along with recommendations on how to use Selenium for testing Django projects)

Let me know what you think about all this.

**Comment by mixxorz** [comment]
I'm for all these ideas!

I'm curious how you think the helpers will work though?

**Comment by bittner** [comment]
The "helpers" (for selenium) I referred to are probably better placed in a separate, independent package. One example for such a package to allow writing more concise, more pythonic Selenium tests is [pylenium](https://pypi.python.org/pypi/pylenium).

**Personal note:** The specific (but arguable) disadvantage I see with `pylenium` is that it overrides existing methods, hence existing Selenium code would be incompatible. It would also be impossible to switch back to "vanilla Selenium" (or mix both worlds) once you write pylenium flavored code.
