### ISSUE TITLE
Looking for (co-)maintainer!  🔥🙏🦠🔥🐍

### ISSUE THREAD

**Issue by bittner** [behave/behave-django#129]
This project is looking for active contributors that are ready to take on responsibility for a future roadmap! (NB: Not only a single feature.)

Due to very heavy load at work I can hardly follow the email notifications. I don't want to abandon this project though, so please if you're interested in taking on responsibility for the _product_ "behave-django", let me know.

There are a few interesting PRs out there that I'd like to integrate asap, but we really need to be sure we're doing the right thing. The code base needs to stay slick and solid. _behave-django_ ideally stays just a very slim, barely noticeable integration layer.

Please let me know with a thumbs up or a comment that you're interested!
Peter

**Comment by bittner** [comment]
@jenisys Could you please add @kingbuzzman to our [behave-django-developers](https://github.com/orgs/behave/teams/behave-django-developers) team, please?

Now [that you volunteered](https://github.com/behave/behave-django/pull/130#issuecomment-1008991519) there's no going back! :smile:

**Comment by kingbuzzman** [comment]
😅

**Comment by jenisys** [comment]
> @jenisys Could you please add @kingbuzzman to our [behave-django-developers](https://github.com/orgs/behave/teams/behave-django-developers) team, please?

DONE.
