### ISSUE TITLE
Migrations data is invalid when testing

### ISSUE THREAD

**Issue by sih4sing5hong5** [behave/behave-django#15]
I inserted some data in my migrations.

I can use them in unittest.

But when I ran `behave`, it got `ObjectDoesNotExist` exception.

I traced the code, the `main` function in `behave/__main__.py`
```
    runner = Runner(config)
```
Before this line, they were in database.
After this, got empty in my database.

How should I trace code to fix this problem?

PS: pip freeze
```
behave==1.2.5
behave-django==0.3.0
```

**Comment by bittner** [comment]
This support question needs more details.

* Stack trace of the exception
* Ideally, access to your source code - or a code sample that helps
* How do you run behave from the command line? (Exact instructions on how to reproduce the problem would help.)

**Comment by bittner** [comment]
I'm closing this as a support question with lack of activity, maybe solved by the OP themselves.

Feel free to supply the missing information as outlined above, and reopen to issue if needed.

**Comment by codeZeilen** [comment]
As I am currently seeing a similar issue (data added through migrations not visible anymore) I just wanted to quickly do a sanity check: Does behave-django support data provided by migrations? 

I quickly took a look at the behave-django implementation and could not find an obvious reason why it should not. 

Thanks for the integration btw!

**Comment by bittner** [comment]
I'm not 100% sure I understand the question. In general, what is supported by Django is supported by behave-django.

You have to provide more details of you want us to analyze the issue.

**Comment by codeZeilen** [comment]
Actually, that already answered my question :) Just wanted to make sure that my assumption was correct. Sorry to bother you with something that trivial (the behavior is just so weird that I am probably missing something obvious).

**Comment by a8568730** [comment]
I encounter the same problem.
I run a feature file with two scenarios, and they all need migrations data. The run script will failed at scenario B due to database is flushed instead rolled back.
```
Feature:  
 	Scenario: A 
		Given ...
		 When ...
		 Then  ...

        # After A, the database is flushed

	Scenario: B
		Given ...
		 When ...
		 Then ...
```

I run tests with `--simple` and it works.
```
python manage.py behave --simple 
```

The behave-django says option [--simple](https://behave-django.readthedocs.io/en/stable/usage.html#simple) as:
```
--simple
Use Django’s simple TestCase which rolls back the database transaction after each 
scenario instead of flushing the entire database. Tests run much quicker, however HTTP 
server is not started and therefore web browser automation is not available.
```
