### ISSUE TITLE
Coverage advice breaks m2m queries.

### ISSUE THREAD

**Issue by BillSchumacher** [behave/behave-django#152]
Reloading a module(s) causes Django to throw an error during testing:

```
django.core.exceptions.FieldDoesNotExist: User_groups has no field named 'None'
```

and 

```
django.core.exceptions.FieldDoesNotExist: User_user_permissions has no field named 'None'
```

When using a custom User model, maybe using the default as well.

I spent more time than I care to admit troubleshooting this, hopefully it helps someone else.

**Comment by BillSchumacher** [comment]
In case anyone is wondering you can just do `coverage run manage.py behave` instead.

**Comment by bittner** [comment]
Thank you, @BillSchumacher, for pointing out that invoking `coverage run` is sufficient for measuring coverage! :1st_place_medal: 

I added this advice to the docs. :rocket:
