### ISSUE TITLE
Landscape badge not being updated

### ISSUE THREAD

**Issue by bittner** [behave/behave-django#19]
I've noticed that builds on Landscape aren't triggered anymore.

@mixxorz Can you check whether you can (re)connect the GitHub repository to Landscape? There is something broken here. If you don't have the necessary permissions either @jenisys must connect the repo to Landscape.

Cheers!

**Comment by mixxorz** [comment]
It seems to be working?

<img width="330" alt="screenshot 2016-08-24 18 16 45" src="https://cloud.githubusercontent.com/assets/3102758/17927228/381211da-6a27-11e6-9fc1-cf92abbf1579.png">

**Comment by bittner** [comment]
Weird though, between 17 Apr (commit 10d401c) and yesterday Landscape didn't pick any commit. That are 8 (eight) commits. And I'm pretty sure when I opened this issue yesterday [build #6](https://landscape.io/github/behave/behave-django/6) was the latest one.

Did you reconnect the service, or log in and that made that happen automagically?

If this is fixed now, good. We should keep an eye on that in any case.

**Comment by mixxorz** [comment]
I didn't do anything. Maybe it was my logging in, but that's unlikely since I didn't check it on Aug 23. Oh well. Let's observe it.

**Comment by bittner** [comment]
@mixxorz Can you check why Landscape isn't running a build for PRs? - See PR #20, for example.

Maybe this needs to be configured in the Landscape account. Maybe this is an issue of GitHub repo permissions. A Landscape build should run for PRs, though. This gives important feedback. (I know this is working on other repos, such as [pytest-django](https://github.com/pytest-dev/pytest-django/).)

**Comment by mixxorz** [comment]
<img width="784" alt="screenshot 2016-08-26 13 14 56" src="https://cloud.githubusercontent.com/assets/3102758/17994866/2f93d6ba-6b8f-11e6-9f87-a81bc9b312d3.png">

This is for #21. I haven't changed anything but the Landscape checks seem to be running.
