### ISSUE TITLE
Switch from optparse to argparse

### ISSUE THREAD

**Issue by bittner** [behave/behave-django#2]
As Django 1.9 complains with a deprecation warning (and more and more developers start using Django 1.9) we should consider switching to [argparse](https://docs.python.org/3.4/library/argparse.html) in a backward-compatible manner. Affected code locations:
* [behave_django/parser.py](https://github.com/behave/behave-django/blob/master/behave_django/parser.py#L1)
* [behave_django/management/commands/behave.py](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py#L2)

## Compatibility Details

Until Django 1.7 optparse's `make_option` is used for the `option_list`. The implementation of our management command pretty much depends on that. Django 1.8 makes the switch finally to argparse. I fear an implementation change on our side will probably have to follow their approach and may need to consider the Django version in use.

### See Also
* https://github.com/django/django/blob/1.7/django/core/management/base.py#L184
* https://github.com/django/django/blob/1.8/django/core/management/base.py#L224
* [Python optparse make_option() equivalent in argparse](http://stackoverflow.com/questions/14387540/python-optparse-make-option-equivalent-in-argparse) (StackOverflow)

## Historical Note

This issue is a continuation of [issue 24](https://github.com/mixxorz/behave-django/issues/24) in the original repository location at `mixxorz/behave-django`.

**Comment by bittner** [comment]
@mixxorz Do you have an idea how to fix this in [parser.py](https://github.com/behave/behave-django/blob/master/behave_django/parser.py#L21)?

**Comment by jenisys** [comment]
Search for ``argparse`` solutions. AFAIK there is a related use case and how to solve it in ``argparse`` how to handle unknown options with parsers or subparsers.
