### ISSUE TITLE
Integrating with jenkins

### ISSUE THREAD

**Issue by hovi** [behave/behave-django#24]
Hey, 

I tried this project and it works very well with my bdd scenarios. I would like to integrate it with jenkins same way I am integrating my unit tests using django-jenkins to see the results in dashboard.

Is there way to do it? If there isn't, could you point me into right direction?

**Comment by bittner** [comment]
I believe this is not strictly related to this project, the integration of behave and Django.

Behave allows you to create XML reports in junit format, e.g. in your [behave configuration file](http://behave.readthedocs.io/en/latest/behave.html?highlight=junit#configuration-files) add:
``` ini
# -- your behave configuration file (.behaverc, behave.ini, setup.cfg)
[behave]
junit = yes
junit_directory = tests/reports
```
Then the rest of the integration with Jenkins should just work [as usual with jUnit](https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Plugin).

**Comment by hovi** [comment]
Perfect, thanks!
