### ISSUE TITLE
Fix navigation drawbacks in docs

### ISSUE THREAD

**Issue by bittner** [behave/behave-django#3]
The documentation has a substantial drawback when it comes to navigating through content.

### Problem example

See the [Contributing](https://pythonhosted.org/behave-django/contribute.html) chapter. How do you get back to the welcome page, for example?

This issue seems to be inherent to the Alabaster theme. Other projects have the same problem, see e.g. the [behave docs](http://pythonhosted.org/behave/django.html), but it's less relevant there because the docs have the behave "logo" (the image with the words box) that takes you home. We should probably have something similar.

- Can we fix the scarce navigation via some configuration switch? ([Sphinx](http://www.sphinx-doc.org/en/stable/config.html#confval-html_sidebars), [Alabaster](https://pypi.python.org/pypi/alabaster))
- We should probably come up with a (Pony) logo and add it as a "home link" to the docs.

### Logo ideas

* [Yet unused Django mascots](http://mirskytech.com/django-iconography-pony-critter/) (Andrew Mirsky)
* Combination of Django and behave. (A Pony and Given-When-Then)

_"Given a pony, when I run behave with behave-django, then my project has awesome tests."_

**Comment by jenisys** [comment]
@bittner 
Maybe sphinx-bootstrap-theme solves these problems (in addition to using a logo).
The title-bar is always present. Therefore, you always have a link to the master-page.
SEE ALSO: https://github.com/ryan-roemer/sphinx-bootstrap-theme

EXAMPLE:
![behave example_docs_header](https://cloud.githubusercontent.com/assets/371945/13968906/b5618944-f07f-11e5-8339-b10f4841251f.png)

**Comment by bittner** [comment]
The [Alabaster documentation](http://alabaster.readthedocs.io/en/latest/customization.html#theme-options) mentions a few options that may fix the issue (apart from the logo, apparently):

- `show_related = True`
- `extra_nav_links = { ... }`

Optionally,
- `fixed_sidebar = True` may also be nice for the lengthy [Usage page](https://pythonhosted.org/behave-django/usage.html).

They need to be added to the [`html_theme_options`](https://github.com/behave/behave-django/blob/master/docs/conf.py#L119) dict, IIUC.

@mixxorz Can you try whether these options help to create a more meaningful navigation in the sidebar?

**Comment by bittner** [comment]
I've moved the "create logo" part of this issue to a separate issue, so we can close this one as soon as PR #21 is merged.

**Comment by bittner** [comment]
Fixed via #21.
