### ISSUE TITLE
Add Python 3.6 to test matrix

### ISSUE THREAD

**Issue by mixxorz** [behave/behave-django#32]
I tried to do this earlier, but because Python 3.6 isn't included in travis' base image, I couldn't get it to work properly.

Related issue: https://github.com/travis-ci/travis-ci/issues/4990

**Comment by bittner** [comment]
Do you have an error message we can look at?

The issue you're mentioning does not affect Python 3.5 for our test runs. It may well be that simply specifying 3.6 in [tox.ini](https://github.com/behave/behave-django/blob/master/tox.ini#L9-L11) and the [Travis configuration](https://github.com/behave/behave-django/blob/master/.travis.yml#L5-L14) makes it all work. As per https://github.com/travis-ci/docs-travis-ci-com/pull/903 Python 3.6 is supported.

Let me note again that I would prefer to remove [the explicit mentioning](https://github.com/behave/behave-django/blob/master/tox.ini#L15-L19) of `basepython`, which is implicitly supported by tox. Would be one thing less we need to update in the tox configuration.

**Comment by bittner** [comment]
Django 1.11 will be the [first release supporting Python 3.6](https://docs.djangoproject.com/en/dev/releases/1.11/). So, we still have time to address the issue.

**Comment by mixxorz** [comment]
Turns out, our tests were only working because:

* We set `python: 3.5` which means travis will explicitly install Python 3.5 on the test vm
* The base image Travis uses includes Python 2.7, 3.3, and 3.4

So when I set `python` to `3.6`, tests running on 3.5 broke because it couldn't find that instance. The only way we can get the python versions we want is to specify multiple versions in `.travis.yml`, but it isn't that straightforward because we're using tox and... it was 11pm and I wanted to sleep so I gave up. 😆 

I'll push up a new branch and you can take a look at what I did.

**Comment by bittner** [comment]
Testing against Python 3.5 and 3.6 on the same build image is [now possible](https://github.com/travis-ci/travis-ci/issues/4990#issuecomment-310824690). Do you want to give that a shot again, @mixxorz?

**Comment by bittner** [comment]
Any plans to give it a shot again, @mixxorz?
