### ISSUE TITLE
--noinput

### ISSUE THREAD

**Issue by hovi** [behave/behave-django#39]
Hi, when I run normal tests using `test` management command and test database already exists, command line asks me if I want existing database to be deleted, ex:
```
Creating test database for alias 'default'...
Got an error creating the test database: (1007, "Can't create database 'test_project'; database exists")
Type 'yes' if you would like to try deleting the test database 'test_project', or 'no' to cancel:
```

Same prompt can popup for `behave` command.

`test` management command (and many other) have --noinput parameter to suppress these prompts and always confirm/overwrite:
https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-test-noinput

Would it be possible to add `--noinput` to `behave` command as well?

**Comment by bittner** [comment]
Then it may also be useful to add [more supported switches](https://docs.djangoproject.com/en/1.11/ref/django-admin/#test), such as `--failfast` and `--reverse`.

If you want to try to prepare a PR take a look at the [behave management command](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py).

**Comment by hovi** [comment]
Alright, here it is.
