### ISSUE TITLE
behave attempts to install fixtures each time and fails since they already exist

### ISSUE THREAD

**Issue by deecodameeko** [behave/behave-django#41]
Hi,

I have a couple of scenarios, all of which need the same set of fixtures. After the first scenario finished, behave attempts to re-install the fixtures even though they've been loaded already. I've tried setup_databases and teardown_databases thinking that would flush the fixtures. I've even tried calling "flush" directl from django's call_command. 

I'm not sure the best way to manage my fixtures. As part of my django.setup() I already call initial_data to load my db...which doesn't seem to be accessible unless I use fixtures in before_scenario.

How do I remove my fixtures after each scenario and prevent the error. OR how do I only load the fixtures once?

**Comment by bittner** [comment]
If you resolve your own situation please leave a comment to make future visitors profit from your insights.

Thank you!

**Comment by deecodameeko** [comment]
I moved setup_databases and teardown_databases to before_all and after_all and no longer needed to conditionally load the fixtures for my tests. What I still don't understand though is why the initial_data loaded when django starts aren't accessible in my test like my site definitions and users.

**Comment by mixxorz** [comment]
Can you try using the `restructure-testcase` branch and see how it affects your tests?
