### ISSUE TITLE
Feature proposal: register fixtures for any 'step_impl'

### ISSUE THREAD

**Issue by sebastianmanger** [behave/behave-django#42]
# Prerequisites
I am adding behave-django to an old-ish project, which provides many json-fixtures. So I am working with various fixtures, and many different steps. As fixtures are loaded in ```environment.py```, knowing which fixtures are loaded for a given ```step_impl``` is not always transparent - at least for me. I have therefore developed a decorator for fixtures, which can be applied to any ```step_impl```

The decorator accepts a list of strings that are then loaded in the ```before_scenario``` in the ```environment.py```. As I prefer callables to json-fixtures, the decorator also accepts paths to callables.

# Example
This is a step:
`@fixtures('languages.json', 'behave.fixtures.pages.wagtail_page')`
`@when('someone does something')`
`def step_impl(context):`
`    ...`

In the ```environment.py``` - ```before_scenario```, callables for all steps of given scenario are executed, and all other files are appended to ```context.fixtures```

# Question
So - please let me know in case you'd like me to provide a pull request, or if you consider this too specific for my project. Thanks a lot for your efforts!

**Comment by bittner** [comment]
Sounds like a good idea to me. Both the closer context to the implementation and the ability to use callables.

**Comment by mixxorz** [comment]
Merged in #43
