### ISSUE TITLE
New port for each scenario...

### ISSUE THREAD

**Issue by matrixise** [behave/behave-django#52]
I use Django + Behave + Selenium for the functional tests.

I just execute `python manage.py behave`, for each Scenario, there is a new Django instance (I say that, but in fact, for each test, the port of the live_server changes each time, it seems strange.

Do you know why?

Thank you

**Comment by matrixise** [comment]
in fact, the issue is because in the BehaveHooksMixin class, we call the setUpClass method of the test_class class and this one will use the setUpClass of LiveServerTestCase.

but I think I have a blocking issue with this behaviour, because when I execute a lot of scenario in this configuration, my process is suspended and I don't know why :-(

maybe with gdb + python I will discover the issue.

**Comment by bittner** [comment]
Sounds like you have a serious problem. Try simplifying your tests. Run them separately, one after the other, manually, and make sure the LiveServerTestCase shuts down cleanly. Writing tests also needs clean code and proper programming.

> for each test, the port of the live_server changes each time, it seems strange.

That, in fact, seems very plausible. Especially with your additional information:

> I think I have a blocking issue

When the Django LiveServerTestCase is not shut down successfully the Django runserver instance occupies a port, and when Django is asked to fire up the next runserver for such a test case then it will increment the port number until it finds a free one to use.

I'm not even sure what to suggest first. Fix your tests, or fix your code first. What you describe sounds like a mess. I apologize. Try running [flake8](http://flake8.pycqa.org) and [pylint](https://www.pylint.org) over both your code base and your test code, then try again.
