### ISSUE TITLE
Reload data migrations after flush

### ISSUE THREAD

**Issue by stereoshoots** [behave/behave-django#60]
Hello.

I have data migrations in my app. Migrations are being executed once after database creation. After scenario database is being flushed except django's data (post_migrate). What is the best way to reload my own data migrations after each scenario? 

Thanks

**Comment by stereoshoots** [comment]
Or maybe a proper way to delete my database and recreate everything after each scenario

**Comment by bittner** [comment]
Please, [take a look at the docs](http://behave-django.readthedocs.io/en/stable/usage.html#database-transactions-per-scenario) to see if this helps you further.

**Comment by stereoshoots** [comment]
Bittner, not sure how the #database-transactions-per-scenario will help in my case. Сan you more specifically explain what actions need to be taken to reload my data migrations?

Thank you.

**Comment by bittner** [comment]
You simply run a migration as you would in Django. The sections "Database transactions per scenario", "django_ready hook", and "Fixture loading" in the documentation are where you should look to understand how similar use cases are handled.

**Comment by bittner** [comment]
Closing as this is neither a bug report nor an enhancement request.

Please use Gitter for support questions.
