### ISSUE TITLE
Django Versions for supporting behave-django

### ISSUE THREAD

**Issue by xiaoleATRI** [behave/behave-django#69]
Hi, there:

in README

> behave-django is tested against the officially supported combinations of Python and Django (Django 1.8, 1.9, 1.10, 1.11, 2.0 on Python 2.7, 3.3, 3.4, 3.5, 3.6, excluding the aged Python 3.2).

However, in your repo, requirements.txt enforces Django to be upgraded to 1.11
`Django>=1.11`

Can you clarify the Django Version? As of now, latest behave-django is working well in Django 1.9 for me

Thanks,

**Comment by bittner** [comment]
You're right, thank for bringing this up. :+1: 

I've fixed this a few days ago [on a feature branch](https://github.com/behave/behave-django/pull/68/files#diff-88b99bb28683bd5b7e3a204826ead112), but the change is not yet merged into `master`. I make sure this happens in due time.

**Comment by bittner** [comment]
As for clarifying, we're trying to stick to the versions [officially supported by Django](https://www.djangoproject.com/download/#supported-versions). The related Python versions are taken [from the classifiers displayed on PyPI](https://pypi.org/project/Django/).

This is mainly to avoid promoting the use of outdated versions of Django (which may be dangerous for you and your users).

Older versions of Django will still work, most probably, but we're not explicitly verifying this fact (using Travis CI).

**Comment by bittner** [comment]
Fixed via 6228932e58d.
