### ISSUE TITLE
How to configure where to find fixtures?

### ISSUE THREAD

**Issue by zadigus** [behave/behave-django#75]
Hi, 

I am struggling letting behave know where my fixtures are. Currently, I have a `shopozor_features` folder at the root of my project containing all my features. This folder is provided in the `setup.cfg` file like this:

```
[behave]
paths = shopozor_features
```
Currently, my features folder is very small:

```
shopozor_features
  - Authentication
    - LogUserIn.feature
  - fixtures
    - user-data.json
  - steps
    - logUserIn.py
  - environment.py
```

Here's the code of my `environment.py`: 

```
def before_scenario(context, scenario):
    context.fixtures = ['user-data.json']

def django_ready(context):
    context.test.client = ApiClient(user=AnonymousUser())
    context.django = True
```

Now, when I use it in my step, behave looks for the fixture file at the root of my project. How do I let behave know that the fixture file is located under `shopozor_features/fixtures/user-data.json`? I could of course write this:

```
def before_scenario(context, scenario):
    context.fixtures = ['shopozor_features/fixtures/user-data.json']
```

but my little finger tells me that there must be a way to tell behave that all the fixtures are located in the folder `shopozor_features/fixtures`. How do I achieve this?

**Comment by bittner** [comment]
There is no such thing as configuring where to find fixtures, at least not in behave-django. You can configure this [in Django](https://docs.djangoproject.com/en/stable/howto/initial-data/#where-django-finds-fixture-files), but this should not even be needed.

The misconceptions I see from your example above is that you seem to think fixtures belong to the test setup, while they actually belong to one of your Django apps. See [our test app](https://github.com/behave/behave-django/tree/master/tests/test_app) for reference (note the `fixtures/` folder).

behave-django does [close to nothing](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L114) with regard to fixture loading, in the end this is essentially all Django's [TransactionTestCase](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#django.test.TransactionTestCase.fixtures) that is doing the work.

**Comment by bittner** [comment]
For DRF see [this StackOverflow answer](https://stackoverflow.com/questions/25297541/django-rest-framework-loading-fixtures-in-an-apitestcase). Let us know if that helped!
