### ISSUE TITLE
[Question] Set server host and port for one scenario

### ISSUE THREAD

**Issue by adam-d-wojnarowski** [behave/behave-django#77]
I have one scenario inside of a feature file where the LiveServer needs to be running on port 8000 due to an external service I have no control over expecting it to be running there.

I've tried setting the port value in BehaviorDrivenTestCase inside of before_scenario but that causes the scenario AFTER the current one to run on port 8000.

I've also tried setting the port in before_all in the same manner and running all the tests on the same port but that causes an address in use error since the server isn't torn down before the next scenario starts.

Is there a "best practice" to setting the port for a scenario? I can work around this by creating a scenario before the one that needs to be ran on port 8000 who's sole purpose is to set the port number but that doesn't seem like a good solution.

**Comment by bittner** [comment]
Let's see ...

- [BehaviorDrivenTestCase](https://github.com/behave/behave-django/blob/master/behave_django/testcase.py#L26) is a [LiveServerTestCase](https://docs.djangoproject.com/en/stable/_modules/django/test/testcases/#LiveServerTestCase), which is instantiated in the [setup_testclass() method](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L65) run in [any before_scenario() call](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L113) by [monkey_patch_behave](https://github.com/behave/behave-django/blob/master/behave_django/management/commands/behave.py#L148).
- If you set the `port` attribute on the `testcase_class` (the attribute of the test runner) the port value should be used by Django when it instantiates the `LiveServerTestCase`. Hence, `BehaviorDrivenTestRunner.testcase_class.port = 8000`.

Now, we only need to find out _where_.

**Comment by bittner** [comment]
> I've tried setting the port value in BehaviorDrivenTestCase inside of before_scenario but that causes the scenario AFTER the current one to run on port 8000.

Can you share the code that you use for doing that? Because, if you do this on the class _before_ it is instantiated this should work fine. After the scenario you may need to reset the port value to 0, probably.

**Comment by adam-d-wojnarowski** [comment]
`Here's my before_scenario,

     def before_scenario(context, scenario):
         BehaviorDrivenTestCase.port = 0
         if "My Scenario" == scenario.name:
              BehaviorDrivenTestCase.port = 8000`

context.test during my scenario reveals that 
`context.test.live_server_url = u'http://localhost:38863'`
`context.test.port = 8000`

While the next scenario is running the values are
`context.test.live_server_url = u'http://localhost:8000'`
`context.test.port = 0`

**Comment by bittner** [comment]
According to [the code](https://github.com/behave/behave-django/blob/master/behave_django/environment.py#L110-L116) setting the port number on the test case class in `before_scenario` should result in a `LiveServer` reachable on the port you specified in all other hooks related to the scenario.

What value returns [context.get_url()](https://behave-django.readthedocs.io/en/stable/usage.html#web-browser-automation) when you run it in the [django_ready hook](https://behave-django.readthedocs.io/en/stable/usage.html#django-ready-hook)?

And no, there is no "best practice" on overriding the `context.base_url` port. You should probably be mocking the external service to make your test independent.

**Comment by bittner** [comment]
Feel free to reopen or comment if you still need help.
