### ISSUE TITLE
Dev-server has to already be running?

### ISSUE THREAD

**Issue by nhill-cpi** [behave/behave-django#86]
Hi,

I can't figure out what I'm missing. I'm just starting to use behave-django, and I'm finding that my tests run, but fail, when my Django dev-server at 127.0.0.1:8000 is not _already_ running. When it is _already_ before I start the tests, the tests pass. I thought behave-django starts a dev server in the background, so I believe I'm missing something very basic. Can you help me out?

Thanks.

**Comment by nhill-cpi** [comment]
When I print `context.get_url()`, I get http://localhost:56208

**Comment by bittner** [comment]
Can you share with us what the problem was? -- How did you run the tests?

Is there something we can improve in the documentation, maybe? (see also [the survey on Gitter](https://gitter.im/behave/behave-django?at=5c72a94f1f1463042112097a))

**Comment by nhill-cpi** [comment]
@bittner  The problem was that I had something like `context.browser.get('http://localhost:8000)` instead of `context.browser.get(context.get_url())`. The second works and not the first b/c the dev server being spun up by the behave tests was not running at 8000. 

I had a little bit of a hard time why the dev server wasn't running on port 8000, and then why I couldn't set it to run on 8000. The documentation has this: "You can access the test HTTP server from your preferred web automation library via context.base_url (normally, this would be set to http://localhost:8000)" but that's all I could find about accessing the HTTP server.

**Comment by bittner** [comment]
> (normally, this would be set to http://localhost:8000)

We probably should remove that bit if text from the documentation. It's from ancient times, before the Django runserver started letting the host deal with allocating the next available port.

Would you care to update the docs and place a PR for that?

**Comment by nhill-cpi** [comment]
Sure, I'll do that.
