### ISSUE TITLE
Prevent database from being flushed after each scenario?

### ISSUE THREAD

**Issue by nhill-cpi** [behave/behave-django#87]
Is there any way to prevent the database from being flushed after each scenario? Thanks.

**Comment by bittner** [comment]
Please use the [Gitter room](https://gitter.im/behave/behave-django) for these types of questions!

The answer is twofold:

- You shouldn't try to do something like that when you write your tests properly. Tests should be isolated and start from a clean setup (for each scenario).
- There are [command line options](https://behave-django.readthedocs.io/en/latest/usage.html#command-line-options) (in the docs) that maybe do what you want, partially. But you really should know what you're doing.
