### ISSUE TITLE
Docs for running tests need updated path for manage.py

### ISSUE THREAD

**Issue by pydolan** [behave/behave-django#93]
On https://behave-django.readthedocs.io/en/latest/contribute.html, all commands using `manage.py` should be updated to `tests/manage.py` since it is implied that the tests be run from the root of the project.  

Note: If one tries to run the tests from within the `tests` directory, the `py.test` tests fail and Behave cannot find the `steps` directory since the Behave config is not defined (since tox.ini is in the parent directory).

**Comment by bittner** [comment]
Thanks for pointing this out!

- This should be updated to `tox -l` and `tox -e py37-django21` (example). The testing docs are from the early days when we had no Tox in the project yet.
- Installing the dev requirements should be mentioned to be optional. (There's really just `tox`, everything else is installed automatically during the test runs.)

In short, all references suggesting manual setup of a development environment should be removed or marked optional. All references suggesting to run something other than `tox` likewise.

**Comment by bittner** [comment]
That should be clearer now.
