### ISSUE TITLE
Tests using the Django test project do not work with newer versions of Django

### ISSUE THREAD

**Issue by pydolan** [behave/behave-django#94]
When setting up my test environment to run tests, pip installed Django 2.2 (since the requirements are for Django >= 1.11).  When running the tests, Django errors about several settings being defined incorrectly.

```
ERRORS:
?: (admin.E404) 'django.contrib.messages.context_processors.messages' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin application.
?: (admin.E408) 'django.contrib.auth.middleware.AuthenticationMiddleware' must be in MIDDLEWARE in order to use the admin application.
?: (admin.E409) 'django.contrib.messages.middleware.MessageMiddleware' must be in MIDDLEWARE in order to use the admin application.
```

I'll push up a PR shortly

**Comment by bittner** [comment]
Add a line for Django 2.2 [in tox.ini](https://github.com/behave/behave-django/blob/master/tox.ini#L10) and go from there (see my explanations in #93). That should work.

The Django version specified in [requirements.txt](https://github.com/behave/behave-django/blob/master/requirements.txt#L2), which is [used by setup.py](https://github.com/behave/behave-django/blob/master/setup.py#L34) is really just for saying, _"Hey, use an older version of behave-django for older Djangos"_ (for people reading source code). We should probably remove it or make it a soft-dependency with setuptools. -- This is the usual, and actually relevant, debate about including dependencies in Python packages.

Thanks for reporting that this is actually an issue!

**Comment by bittner** [comment]
This should work now when you run behave-django off the `master` branch.

**Comment by Adarshptl123** [comment]
Can you explain this

**Comment by bittner** [comment]
There was a release on April 16, 2019 ([v1.3.0](https://pypi.org/project/behave-django/#history)), which [includes the fix to the test project](https://github.com/behave/behave-django/compare/1.2.0...1.3.0) that was added on April 04, 2019 (see link above).

**Comment by adnanrizwee** [comment]
1) Go to settings.py of your project

2) Cut these three lines from MIDDLEWARE_CLASSES :

    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',

3) Now paste the code given below right after MIDDLEWARE_CLASSES :

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

**Comment by bittner** [comment]
@adnanrizwee I'm not sure I understand: You're using both the `MIDDLEWARE_CLASSES` and the `MIDDLEWARE` in your Django settings together? Do you have a specific reason for that? And which Django version do you run?
